import { createClient } from "@/core/supabase/server";
import { MarketingShell, PageHeader } from "@/components/marketing/marketing-shell";

export const metadata = { title: "Terms · WhiteWire" };

export default async function Terms() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  return (
    <MarketingShell signedIn={Boolean(user)}>
      <PageHeader title="Terms of Service" subtitle="The short version" />
      <div className="space-y-5 text-sm text-muted-foreground">
        <p>By using WhiteWire you agree to use it lawfully and to keep your account credentials secure. You are responsible for the API keys you add and any usage or costs your model provider bills you for.</p>
        <p>WhiteWire is provided “as is” without warranties. We are not liable for outputs generated by third-party models or for provider outages.</p>
        <p>You retain ownership of the content you create. You may stop using the service and delete your account at any time.</p>
        <p>We may update these terms; continued use after changes constitutes acceptance.</p>
      </div>
    </MarketingShell>
  );
}
